// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXMtp6_biG4TJZzOZnvWtboZ0tpEZA0tY',
    appId: '1:326120752538:web:662863c40edb97e64ca623',
    messagingSenderId: '326120752538',
    projectId: 'restaurant-recommendatio-24c81',
    authDomain: 'restaurant-recommendatio-24c81.firebaseapp.com',
    storageBucket: 'restaurant-recommendatio-24c81.firebasestorage.app',
    measurementId: 'G-93V0PH5X0E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpk7NPDI2-Xn0nT0X0Xvx0MeHV5FmdkM8',
    appId: '1:326120752538:android:ae84a2cd29b2821b4ca623',
    messagingSenderId: '326120752538',
    projectId: 'restaurant-recommendatio-24c81',
    storageBucket: 'restaurant-recommendatio-24c81.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnoNc4Q9T-i0acg_7mPdLb8uR9WuZ7sVk',
    appId: '1:326120752538:ios:f06ddda6bb873b7e4ca623',
    messagingSenderId: '326120752538',
    projectId: 'restaurant-recommendatio-24c81',
    storageBucket: 'restaurant-recommendatio-24c81.firebasestorage.app',
    iosBundleId: 'com.example.smartFoodV1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnoNc4Q9T-i0acg_7mPdLb8uR9WuZ7sVk',
    appId: '1:326120752538:ios:f06ddda6bb873b7e4ca623',
    messagingSenderId: '326120752538',
    projectId: 'restaurant-recommendatio-24c81',
    storageBucket: 'restaurant-recommendatio-24c81.firebasestorage.app',
    iosBundleId: 'com.example.smartFoodV1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXMtp6_biG4TJZzOZnvWtboZ0tpEZA0tY',
    appId: '1:326120752538:web:c33d27fa075ffd164ca623',
    messagingSenderId: '326120752538',
    projectId: 'restaurant-recommendatio-24c81',
    authDomain: 'restaurant-recommendatio-24c81.firebaseapp.com',
    storageBucket: 'restaurant-recommendatio-24c81.firebasestorage.app',
    measurementId: 'G-2DZB4M1QPQ',
  );
}
