// import 'package:flutter/material.dart';
// import 'package:firebase_auth/firebase_auth.dart';
// import 'package:shared_preferences/shared_preferences.dart';
// // import 'email_link_sent_screen.dart'; // We'll create this next
// // filepath: lib/main.dart
// import 'package:firebase_core/firebase_core.dart';
// import 'package:firebase_dynamic_links/firebase_dynamic_links.dart';
// import '../firebase_options.dart'; // Make sure this is generated by FlutterFire CLI
// // filepath: lib/screens/email_link_sent_screen.dart

// // Import your screens
// import 'welcome_screen.dart'; // Your initial screen
// import 'home_screen.dart';
// import 'select_preferences_screen.dart'; // For continuing registration
// import 'login_screen.dart'; // Or your main entry screen

// class EmailLinkRegisterScreen extends StatefulWidget {
//   const EmailLinkRegisterScreen({super.key});

//   @override
//   State<EmailLinkRegisterScreen> createState() => _EmailLinkRegisterScreenState();
// }

// class _EmailLinkRegisterScreenState extends State<EmailLinkRegisterScreen> {
//   final _formKey = GlobalKey<FormState>();
//   final _nameController = TextEditingController();
//   final _emailController = TextEditingController();
//   bool _isLoading = false;

//   // IMPORTANT: Replace with your Dynamic Links domain from Firebase Console
//   final String _yourDynamicLinksDomain = "yourprojectname.page.link";


//   @override
//   void dispose() {
//     _nameController.dispose();
//     _emailController.dispose();
//     super.dispose();
//   }

//   Future<void> _sendSignInLink() async {
//     if (!_formKey.currentState!.validate()) {
//       return;
//     }
//     setState(() {
//       _isLoading = true;
//     });

//     final email = _emailController.text.trim();
//     final name = _nameController.text.trim();

//     // This URL is where the user will be redirected from the email link.
//     // It must be a URL that your app can handle via deep linking.
//     // It should also be authorized in the Firebase console under Authentication > Settings > Authorized domains.
//     // And your dynamic link domain should also be an authorized domain.
//     final actionCodeSettings = ActionCodeSettings(
//       url: 'https://$_yourDynamicLinksDomain/finishSignUp?email=$email', // The link to open in the app
//       handleCodeInApp: true,
//       iOSBundleId: 'com.example.yourAppBundleId', // Replace with your iOS bundle ID
//       androidPackageName: 'com.example.yourAppPackageName', // Replace with your Android package name
//       androidInstallApp: true,
//       androidMinimumVersion: '12', // Optional
//     );

//     try {
//       await FirebaseAuth.instance.sendSignInLinkToEmail(
//         email: email,
//         actionCodeSettings: actionCodeSettings,
//       );

//       // Store email and name to retrieve after the user clicks the link
//       final prefs = await SharedPreferences.getInstance();
//       await prefs.setString('emailForSignIn', email);
//       await prefs.setString('nameForRegistration', name);

//       if (mounted) {
//         Navigator.pushReplacement(
//           context,
//           MaterialPageRoute(builder: (context) => EmailLinkSentScreen(email: email)),
//         );
//       }
//     } on FirebaseAuthException catch (e) {
//       if (mounted) {
//         ScaffoldMessenger.of(context).showSnackBar(
//           SnackBar(content: Text('Failed to send link: ${e.message}')),
//         );
//       }
//     } catch (e) {
//       if (mounted) {
//         ScaffoldMessenger.of(context).showSnackBar(
//           SnackBar(content: Text('An unexpected error occurred: ${e.toString()}')),
//         );
//       }
//     } finally {
//       if (mounted) {
//         setState(() {
//           _isLoading = false;
//         });
//       }
//     }
//   }

//   @override
//   Widget build(BuildContext context) {
//     // Apply Figma styling principles
//     return Scaffold(
//       backgroundColor: const Color(0xFFFFF5F2),
//       appBar: AppBar(
//         title: const Text('Register with Email Link', style: TextStyle(fontFamily: 'SofiaSans', color: Colors.black87)),
//         backgroundColor: Colors.transparent,
//         elevation: 0,
//         iconTheme: const IconThemeData(color: Colors.black87),
//       ),
//       body: SingleChildScrollView(
//         padding: const EdgeInsets.all(24.0),
//         child: Form(
//           key: _formKey,
//           child: Column(
//             crossAxisAlignment: CrossAxisAlignment.start,
//             children: [
//               const Text(
//                 'Create Account',
//                 style: TextStyle(fontFamily: 'SofiaSans', fontSize: 36, fontWeight: FontWeight.bold),
//               ),
//               const SizedBox(height: 8),
//               const Text(
//                 'Enter your name and email. We\'ll send you a magic link to sign in.',
//                 style: TextStyle(fontFamily: 'SofiaSans', fontSize: 16, color: Colors.grey),
//               ),
//               const SizedBox(height: 40),
//               TextFormField(
//                 controller: _nameController,
//                 decoration: InputDecoration(
//                   labelText: 'Full Name',
//                   hintText: 'Your full name',
//                   filled: true,
//                   fillColor: Colors.white,
//                   border: OutlineInputBorder(borderRadius: BorderRadius.circular(16), borderSide: BorderSide.none),
//                 ),
//                 validator: (value) => value == null || value.isEmpty ? 'Please enter your name' : null,
//               ),
//               const SizedBox(height: 20),
//               TextFormField(
//                 controller: _emailController,
//                 keyboardType: TextInputType.emailAddress,
//                 decoration: InputDecoration(
//                   labelText: 'Email',
//                   hintText: 'Your email address',
//                   filled: true,
//                   fillColor: Colors.white,
//                   border: OutlineInputBorder(borderRadius: BorderRadius.circular(16), borderSide: BorderSide.none),
//                 ),
//                 validator: (value) {
//                   if (value == null || value.isEmpty) return 'Please enter your email';
//                   if (!RegExp(r'^[^@]+@[^@]+\.[^@]+').hasMatch(value)) return 'Enter a valid email';
//                   return null;
//                 },
//               ),
//               const SizedBox(height: 40),
//               SizedBox(
//                 width: double.infinity,
//                 height: 56,
//                 child: ElevatedButton(
//                   onPressed: _isLoading ? null : _sendSignInLink,
//                   style: ElevatedButton.styleFrom(
//                     backgroundColor: const Color(0xFFFF7F59),
//                     foregroundColor: Colors.white,
//                     shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(30)),
//                   ),
//                   child: _isLoading
//                       ? const CircularProgressIndicator(color: Colors.white)
//                       : const Text('SEND SIGN-IN LINK', style: TextStyle(fontFamily: 'SofiaSans', fontSize: 18, fontWeight: FontWeight.w600)),
//                 ),
//               ),
//             ],
//           ),
//         ),
//       ),
//     );
//   }
// }

// class EmailLinkSentScreen extends StatelessWidget {
//   final String email;
//   const EmailLinkSentScreen({super.key, required this.email});

//   @override
//   Widget build(BuildContext context) {
//     return Scaffold(
//       backgroundColor: const Color(0xFFFFF5F2),
//       appBar: AppBar(
//         backgroundColor: Colors.transparent,
//         elevation: 0,
//         automaticallyImplyLeading: false,
//       ),
//       body: Center(
//         child: Padding(
//           padding: const EdgeInsets.all(24.0),
//           child: Column(
//             mainAxisAlignment: MainAxisAlignment.center,
//             children: [
//               const Icon(Icons.mark_email_read_outlined, size: 100, color: Color(0xFFFF7F59)),
//               const SizedBox(height: 30),
//               const Text(
//                 'Check Your Email',
//                 style: TextStyle(fontFamily: 'SofiaSans', fontSize: 28, fontWeight: FontWeight.bold),
//                 textAlign: TextAlign.center,
//               ),
//               const SizedBox(height: 16),
//               Text(
//                 'We\'ve sent a sign-in link to $email.\nPlease check your inbox (and spam folder) and click the link to complete your registration.',
//                 textAlign: TextAlign.center,
//                 style: const TextStyle(fontFamily: 'SofiaSans', fontSize: 16, color: Colors.grey),
//               ),
//               const SizedBox(height: 40),
//               ElevatedButton(
//                 onPressed: () {
//                   // Navigate to a screen where they can potentially re-enter email or go back to login
//                   Navigator.of(context).pushAndRemoveUntil(
//                     MaterialPageRoute(builder: (context) => const LoginScreen()), // Or WelcomeScreen
//                     (Route<dynamic> route) => false,
//                   );
//                 },
//                 style: ElevatedButton.styleFrom(
//                   backgroundColor: const Color(0xFFFF7F59),
//                   foregroundColor: Colors.white,
//                   padding: const EdgeInsets.symmetric(horizontal: 30, vertical: 15),
//                   shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(30)),
//                 ),
//                 child: const Text('BACK TO LOGIN', style: TextStyle(fontFamily: 'SofiaSans')),
//               )
//             ],
//           ),
//         ),
//       ),
//     );
//   }
// }


// // Global NavigatorKey
// final GlobalKey<NavigatorState> navigatorKey = GlobalKey<NavigatorState>();

// void main() async {
//   WidgetsFlutterBinding.ensureInitialized();
//   await Firebase.initializeApp(
//     options: DefaultFirebaseOptions.currentPlatform,
//   );
//   runApp(const MyApp());
// }

// class MyApp extends StatefulWidget {
//   const MyApp({super.key});

//   @override
//   State<MyApp> createState() => _MyAppState();
// }

// class _MyAppState extends State<MyApp> {
//   @override
//   void initState() {
//     super.initState();
//     _initDynamicLinks();
//   }

//   Future<void> _initDynamicLinks() async {
//     // Handle links that open the app when it's already running
//     FirebaseDynamicLinks.instance.onLink.listen((PendingDynamicLinkData? dynamicLink) async {
//       final Uri? deepLink = dynamicLink?.link;
//       if (deepLink != null) {
//         _handleDeepLink(deepLink);
//       }
//     }).onError((error) {
//       // Handle errors
//       debugPrint('Dynamic Link onLink error: $error');
//     });

//     // Handle link that opened the app if it was closed
//     final PendingDynamicLinkData? initialLink = await FirebaseDynamicLinks.instance.getInitialLink();
//     if (initialLink != null) {
//       final Uri deepLink = initialLink.link;
//       _handleDeepLink(deepLink);
//     }
//   }

//   Future<void> _handleDeepLink(Uri deepLink) async {
//     debugPrint('Handling deep link: $deepLink');
//     final FirebaseAuth auth = FirebaseAuth.instance;

//     if (auth.isSignInWithEmailLink(deepLink.toString())) {
//       try {
//         final prefs = await SharedPreferences.getInstance();
//         final email = prefs.getString('emailForSignIn');
//         final name = prefs.getString('nameForRegistration'); // Retrieve name

//         if (email != null) {
//           final UserCredential userCredential = await auth.signInWithEmailLink(
//             email: email,
//             emailLink: deepLink.toString(),
//           );

//           // User signed in
//           User? user = userCredential.user;
//           debugPrint('Successfully signed in with email link: ${user?.uid}');
//           await prefs.remove('emailForSignIn'); // Clean up
//           await prefs.remove('nameForRegistration');


//           if (user != null && name != null) {
//             // This is a new registration, proceed to preferences
//             // Use navigatorKey if context is not available directly
//             navigatorKey.currentState?.pushAndRemoveUntil(
//               MaterialPageRoute(
//                 builder: (context) => SelectPreferencesScreen(user: user, name: name),
//               ),
//               (route) => false,
//             );
//           } else if (user != null) {
//             // User might be signing in, not registering, or name was lost
//             // Navigate to home or appropriate screen
//              navigatorKey.currentState?.pushAndRemoveUntil(
//               MaterialPageRoute(builder: (context) => const HomeScreen()),
//               (route) => false,
//             );
//           }
//         } else {
//           debugPrint('Email not found in SharedPreferences for sign-in link.');
//           // Handle error: show message to user, e.g., "Invalid link or session expired"
//         }
//       } catch (e) {
//         debugPrint('Error signing in with email link: $e');
//         // Handle error: show message to user
//       }
//     } else {
//         debugPrint('Link is not a sign-in with email link.');
//     }
//   }

//   @override
//   Widget build(BuildContext context) {
//     return MaterialApp(
//       navigatorKey: navigatorKey, // Assign the global key
//       title: 'Restaurant App',
//       theme: ThemeData(
//         primarySwatch: Colors.orange,
//         fontFamily: 'SofiaSans', // Assuming you have this font
//       ),
//       home: StreamBuilder<User?>(
//         stream: FirebaseAuth.instance.authStateChanges(),
//         builder: (context, snapshot) {
//           if (snapshot.connectionState == ConnectionState.waiting) {
//             return const Scaffold(body: Center(child: CircularProgressIndicator()));
//           }
//           if (snapshot.hasData) {
//             return const HomeScreen(); // User is logged in
//           }
//           return const WelcomeScreen(); // User is not logged in
//         },
//       ),
//     );
//   }
// }
